import type { Metadata } from "next";
import { Quicksand } from "next/font/google";
import { Space_Mono } from "next/font/google";
import "./globals.css";

const spaceMono = Space_Mono({
  variable: "--font-space-mono", // optional CSS variable
  subsets: ["latin"],
  weight: ["400", "700"], // only available weights
  display: "swap",
});
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });
// const quicksand = Quicksand({
//   variable: "--font-quicksand", // your CSS variable
//   subsets: ["latin"],
//   weight: "variable", // variable font
//   display: "swap",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${spaceMono.variable} antialiased`}>{children}</body>
    </html>
  );
}
